package edu.zespol5.pkhotelbackend.model.user;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;

/**
 * Entity representing a user in the system.
 * <p>
 * The `User` class is used to store user details such as their name, email, password, date of birth, and role.
 * Users can either be clients or administrators based on the assigned role.
 * </p>
 */
@Data
@Entity
@Table(name = "user")
public class User {

    /**
     * Unique identifier for the user.
     * The `id` is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * First name of the user.
     * This field stores the user's first name.
     */
    private String firstName;

    /**
     * Last name of the user.
     * This field stores the user's last name.
     */
    private String lastName;

    /**
     * Email address of the user.
     * This field stores the user's email which is typically used for login and notifications.
     */
    private String email;

    /**
     * Password of the user.
     * This field stores the hashed password for authentication purposes.
     */
    private String password;

    /**
     * Birthdate of the user.
     * This field stores the user's date of birth, which can be used for age verification or personalized features.
     */
    private LocalDate birthDate;

    /**
     * Role of the user within the system.
     * The `role` is an enumeration that can be either `CLIENT` or `ADMIN` and determines the level of access the user has.
     */
    @Enumerated(EnumType.STRING)
    private UserRole role;
}
