import { Room, Standard } from './Room';

export const MOCK_ROOMS: Room[] = [
  new Room({
    hotelId: 1,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg", ""],
  }),
  new Room({
    hotelId: 2,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg"],
  }),
  new Room({
    hotelId: 3,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg"],
  }),
  new Room({
    hotelId: 4,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg"],
  }),
  new Room({
    hotelId: 5,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg"],
  }),
  new Room({
    hotelId: 6,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg"],
  }),
  new Room({
    hotelId: 7,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg"],
  }),
  new Room({
    hotelId: 8,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg", "asdas"],
  }),
  new Room({
    hotelId: 9,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg"],
  }),
  new Room({
    hotelId: 10,
    roomNr: 101,
    name: "Ocean View Suite",
    standard: "Apartament" as Standard,
    places: 4,
    description: "A luxurious suite with a breathtaking view of the ocean elllllllllllllllllllll ooooooooo kureaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
    price: 250,
    imagesUrl: ["/assets/room1.jpg"],
  }),
];
